### PR TITLE
Performance fixes and simplifications for `fem::Form`

### LINKED ISSUE #3644: Reduce and fix `fem::Form::domain` methods
`fem::Form` has four `domain` methods, which is confusing, and they handle memory differently. Some return a std:span and some return a copy of a `std::vector`. This easily leads to memory errors, and in low-level assembly code we have large `std::vector` copies being made.

The number of methods should be reduced, methods with very different memory handling should not have the same name, and copies inside the assembly code should be avoided.

### PR DESCRIPTION
**Pull request by garth-wells**
`fem::Form` had gotten unmanageably  complex, which contributed to some performance bugs (e.g., #3644) and #3645. This change substantially simplifies `fem::Form` without removing functionality, gets it in decent shape for handling 'mixed topology' meshes, and fixes some performance bugs where data was copy returned in performance critical code sections and data was repeatedly re-computed.

The `fem::Form` now always requires a `Mesh` argument. The clears up various ambiguities and possible sources of error.  There are more improvements that can follow this PR. The bugs in `fem::Form` were exposed by improvements that were being made elsewhere.

Resolves #3644 and #3598. See https://github.com/FEniCS/dolfinx/pull/3645#issuecomment-2676765039 for one example of performance improvement.

### CODE REVIEW

**Comment by jorgensd** [comment]
This is a good step towards resolving: https://github.com/FEniCS/dolfinx/issues/3598

File: cpp/dolfinx/fem/Form.h [hunk 1]
```diff
@@ -39,17 +41,109 @@ enum class IntegralType : std::int8_t
...
+  const int tdim = topology.dim();
+
+  std::vector<std::int32_t> mapped_entities;
+  mapped_entities.reserve(entities.size());
+  switch (type)
+  {
+  case IntegralType::cell:
+  {
+    std::ranges::transform(entities, std::back_inserter(mapped_entities),
+                           [&entity_map](auto e) { return entity_map[e]; });
```
Comment (jorgensd) [inline cpp/dolfinx/fem/Form.h:64]: Until we have resolved https://github.com/FEniCS/dolfinx/issues/3371 we need to have a check that `entity_map` does not map to a negative number, as this would cause a segfault later in the code.

File: cpp/dolfinx/fem/Form.h [hunk 2]
```diff
@@ -39,17 +41,109 @@ enum class IntegralType : std::int8_t
...
+  }
+  case IntegralType::exterior_facet:
+  {
+    if (codim == 0)
+    {
+      for (std::size_t i = 0; i < entities.size(); i += 2)
+      {
+        // Add cell and the local facet index
+        mapped_entities.insert(mapped_entities.end(),
+                               {entity_map[entities[i]], entities[i + 1]});
```
Comment (jorgensd) [inline cpp/dolfinx/fem/Form.h:75]: Same comment as above.

File: cpp/dolfinx/fem/Form.h [hunk 3]
```diff
@@ -39,17 +41,109 @@ enum class IntegralType : std::int8_t
...
+      // in `mesh`, so we need to get the facet number from the (cell,
+      // local_facet pair) first.
+      auto c_to_f = topology.connectivity(tdim, tdim - 1);
+      assert(c_to_f);
+      for (std::size_t i = 0; i < entities.size(); i += 2)
+      {
+        // Get the facet index, and add cell and the local facet index
+        std::int32_t facet = c_to_f->links(entities[i])[entities[i + 1]];
+        mapped_entities.insert(mapped_entities.end(),
+                               {entity_map[facet], entities[i + 1]});
```
Comment (jorgensd) [inline cpp/dolfinx/fem/Form.h:90]: Is this correct?
Say we have an exterior facet integral `(cell_0, facet_index_0)` which should be mapped onto a submesh of codim-1. Then the integration entity on the "submesh" is a cell integral for that mesh, and thus the "local facet index" (entities[i+1])" doesn;t really make sense to store. @jpdean am I missing some logic here?

Comment (garth-wells) [reply cpp/dolfinx/fem/Form.h:90]: Code is unchanged from `main`, https://github.com/FEniCS/dolfinx/blob/ead49d0fdd57d2273162ede3484505fa77981001/cpp/dolfinx/fem/Form.h#L511.

File: cpp/dolfinx/fem/Form.h (hunk 1 above)
Comment (garth-wells) [reply cpp/dolfinx/fem/Form.h:64]: Why would it be negative?

This code is unchanged from `main`,  it's just just been moved into a different function: https://github.com/FEniCS/dolfinx/blob/ead49d0fdd57d2273162ede3484505fa77981001/cpp/dolfinx/fem/Form.h#L428

File: cpp/dolfinx/fem/Form.h (hunk 3 above)
Comment (jorgensd) [reply cpp/dolfinx/fem/Form.h]: I am not stating that you have introduced a bug. What I am trying to say is that I don't think we need to add entities[i+1]  for codim 1, and that we could send in 0. I'll let @jpdean comment if he agrees.

File: cpp/dolfinx/fem/Form.h [hunk 4]
```diff
@@ -188,44 +219,137 @@ class Form
...
       {
-        throw std::runtime_error("Integral IDs not sorted");
+        for (auto& [key, integral] : _integrals)
+          vdata.insert({key, std::span(integral.entities)});
       }
+      else
+      {
+        auto it = entity_maps.find(mesh0);
+        if (it == entity_maps.end())
+          throw std::runtime_error("No entity map for the mesh.");
```
Comment (jpdean) [inline cpp/dolfinx/fem/Form.h:271]: This was already checked above, so maybe we could remove above check or just `assert` here?

File: cpp/dolfinx/fem/Form.h [hunk 5]
```diff
@@ -188,44 +219,137 @@ class Form
...
+        if (auto mesh0 = coefficients.at(c)->function_space()->mesh();
+            mesh0 == _mesh)
+        {
+          _cdata.insert({{type, id, c}, std::span(integral.entities)});
+        }
+        else
+        {
+          auto it = entity_maps.find(mesh0);
+          if (it == entity_maps.end())
+            throw std::runtime_error("No entity map for the mesh.");
```
Comment (jpdean) [inline cpp/dolfinx/fem/Form.h:322]: Also checked above

File: cpp/dolfinx/fem/Form.h [hunk 6]
```diff
@@ -378,173 +474,77 @@ class Form
...
+  /// @param id Integral identifier index.
+  /// @param kernel_idx Kernel index (cell type).
+  /// @return An array `domain`, such that:
+  /// - For cell integrals, `domain[i]` is the index of the ith cell `i`
+  /// in the integration domain mesh.
+  /// - For exterior/interior facet integrals, `domain[2*i]` is the
+  /// index of a cell in the integration domain mesh attached to the
+  /// facets `i`, and `domain[2*i + 1]` is the local index of the facet
+  /// relative to the cell.
+  std::span<const std::int32_t> domain_arg(IntegralType type, int rank, int id,
```
Comment (jpdean) [inline cpp/dolfinx/fem/Form.h:507]: I don't think the docs for this function are correct. The returned list contains indices in the meshes that the trial or test functions are defined over, not the integration mesh.

File: cpp/dolfinx/fem/Form.h [hunk 7]
```diff
@@ -378,173 +474,77 @@ class Form
...
   /// @param type Integral type.
-  /// @param i Integral ID, i.e. the (sub)domain index.
-  /// @param mesh The mesh the entities are numbered with respect to.
-  /// @return List of active entities in `mesh` for the given integral.
-  std::vector<std::int32_t> domain(IntegralType type, int i,
-                                   const mesh::Mesh<geometry_type>& mesh) const
+  /// @param id Integral identifier index.
+  /// @param c Coefficient index.
+  /// @return Domain indices for the coefficient function.
+  std::span<const std::int32_t> domain_coeff(IntegralType type, int id,
```
Comment (jpdean) [inline cpp/dolfinx/fem/Form.h:534]: Same issue here

File: cpp/dolfinx/fem/Form.h [hunk 8]
```diff
@@ -606,9 +606,18 @@ class Form
   // True if permutation data needs to be passed into these integrals
   bool _needs_facet_permutations;
 
-  // Entity maps (see Form documentation)
-  std::map<std::shared_ptr<const mesh::Mesh<geometry_type>>,
-           std::vector<std::int32_t>>
-      _entity_maps;
+  // Domain data for argument functions
+  //  [rank_i][IntegralType, integral(id), cell_type] -> entity map
+  std::vector<std::map<
```
Comment (jpdean) [inline cpp/dolfinx/fem/Form.h:611]: I'm think it's fine with storing these here, rather than just the entitiy maps. But, this approach might use more memory than before for some integrals

File: cpp/dolfinx/fem/Form.h [hunk 9]
```diff
@@ -606,9 +606,18 @@ class Form
   // True if permutation data needs to be passed into these integrals
   bool _needs_facet_permutations;
 
-  // Entity maps (see Form documentation)
-  std::map<std::shared_ptr<const mesh::Mesh<geometry_type>>,
-           std::vector<std::int32_t>>
-      _entity_maps;
+  // Domain data for argument functions
+  //  [rank_i][IntegralType, integral(id), cell_type] -> entity map
```
Comment (jpdean) [inline cpp/dolfinx/fem/Form.h:610]: I think "-> entity map" might be a bit misleading here. This gives the mapped entities for the requested [rank_i][IntegralType, integral(id), cell_type]

File: cpp/dolfinx/fem/Form.h (hunk 8 above)
Comment (garth-wells) [reply cpp/dolfinx/fem/Form.h:611]: Any memory change would be zero to minimal because the data can be shared across integrals. The re-computation cost is avoided. Some more work would allow more data sharing for more complex cases.

Major change is avoiding need to store shared pointer to meshes, which was ugly.

File: cpp/dolfinx/fem/Form.h (hunk 3 above)
Comment (jpdean) [reply cpp/dolfinx/fem/Form.h]: Yes, I agree. Though it's probably not a major issue for now

**Review by jpdean — APPROVED** [review]

File: cpp/dolfinx/fem/Form.h (hunk 1 above)
Comment (jorgensd) [reply cpp/dolfinx/fem/Form.h:67]: Entity maps with it current design, stores -1 for entities of the parent mesh that does not exist in the submesh. That is why I have suggested we use a `MeshTags` instance instead, as it allows for a sparse 1-1 map.
