### PR TITLE
Consistency fixes for exterior facet computation

### LINKED ISSUE #1004: `dolfinx.mesh.locate_entities_geometrical` does not give expected result with `GhostMode.shared_facet`
Also related to #1003 

Consider the following assembling a FE vector by integrating a test function on a subset of exterior boundaries located using `dolfinx.mesh.locate_entities_geometrical` and `GhostMode.shared_facet`.

```
import ufl
import dolfinx
from mpi4py import MPI
from petsc4py import PETSc
import numpy as np

def pprint(*msg):
    print("Proc", mesh.mpi_comm().rank, "::", *msg)

mesh = dolfinx.UnitSquareMesh(
    MPI.COMM_WORLD, 2, 2,
    ghost_mode=dolfinx.cpp.mesh.GhostMode.shared_facet)

V = dolfinx.FunctionSpace(mesh, ("CG", 1))
v = ufl.TestFunction(V)

bdry_facet_ids = dolfinx.mesh.locate_entities_geometrical(
    mesh, mesh.topology.dim - 1,
    lambda x: np.isclose(x[1], 0.0),
    boundary_only=True)

bdry_id = 1
pprint("bdry_facet_ids:", bdry_facet_ids)
facets_tags = dolfinx.mesh.MeshTags(mesh, mesh.topology.dim - 1,
                                    bdry_facet_ids, bdry_id)

ds = ufl.Measure("ds", subdomain_data=facets_tags)

l = v*ds(bdry_id)
F = dolfinx.fem.assemble_vector(l)
F.ghostUpdate(addv=PETSc.InsertMode.ADD, mode=PETSc.ScatterMode.REVERSE)

pprint("functional:", F.norm())
```

The output is not as expected in parallel:

```
procs=1
Proc 0 :: bdry_facet_ids: [0 3]
Proc 0 :: functional: 0.6123724356957945
procs=2
Proc 0 :: bdry_facet_ids: []
Proc 0 :: functional: 0.3535533905932738
Proc 1 :: bdry_facet_ids: [1]
Proc 1 :: functional: 0.3535533905932738
```

### PR DESCRIPTION
**Pull request by garth-wells**
- Fix computation of exterior facets for ghosted and non-ghosted meshes. Computes just for owned entities. Does not use any communication.

- Split and rename mesh::locate_entities_geometric. The old `boundary_only` is a rather special case since it is really 'attached to an owned boundary facet *and* satisfies the marker'. For clarity the function has now been split into two (`mesh::locate_entities` and `mesh::locate_entities_boundary`) and it makes the code easier to follow.

- Removed `Topology::on_boundary` since it did not necessarily mark all boundary entities, e.g. for a process it would not mark a boundary vertex that was not attached to a local exterior facet.

Fixes #1004.

### CODE REVIEW

File: cpp/dolfinx/mesh/utils.cpp [hunk 1]
```diff
@@ -725,137 +726,190 @@ Eigen::Array<double, Eigen::Dynamic, 3, Eigen::RowMajor> mesh::midpoints(
...
 
-  // Pack coordinates of all active vertices
-  Eigen::Array<double, 3, Eigen::Dynamic, Eigen::RowMajor> x_active(3, count);
+  // Create entities and connectivities
+  mesh.topology_mutable().create_entities(dim);
+  mesh.topology_mutable().create_connectivity(tdim - 1, dim);
+  mesh.topology_mutable().create_connectivity(tdim - 1, 0);
+  mesh.topology_mutable().create_connectivity(0, tdim);
+  mesh.topology_mutable().create_connectivity(tdim, 0);
+  if (dim < tdim)
```
Comment (jorgensd) [inline cpp/dolfinx/mesh/utils.cpp:824]: This will always be the case, as you throw a runtime error when dim == tdim in line 808.

File: cpp/dolfinx/mesh/utils.cpp [hunk 2]
```diff
@@ -725,137 +726,190 @@ Eigen::Array<double, Eigen::Dynamic, 3, Eigen::RowMajor> mesh::midpoints(
...
+    mesh.topology_mutable().create_connectivity(dim, 0);
 
-  for (std::int32_t i = 0; i < num_vertices; ++i)
+  // Build set of vertices on boundary and set of boundary entities
+  auto f_to_v = topology.connectivity(tdim - 1, 0);
+  assert(f_to_v);
+  auto f_to_e = topology.connectivity(tdim - 1, dim);
```
Comment (jorgensd) [inline cpp/dolfinx/mesh/utils.cpp:830]: I guess in it should be possible to avoid some duplication here if dim == 0, but I am not sure if it is worth it or not.

File: cpp/dolfinx/mesh/Topology.cpp [hunk 3]
```diff
@@ -116,62 +116,38 @@ compute_index_sharing(MPI_Comm comm, std::vector<std::int64_t>& unknown_indices)
...
-  // Copy data, castint 1 -> true and 0 -> false
-  num_cells0.insert(num_cells0.end(), ghost_markers.begin(),
-                    ghost_markers.end());
-  std::vector<bool> interior_facet(num_cells0.begin(), num_cells0.end());
-
-  return interior_facet;
+  return _boundary_facet;
 }
 //-----------------------------------------------------------------------------
+//-----------------------------------------------------------------------------
```
Comment (michalhabera) [inline cpp/dolfinx/mesh/Topology.cpp:150]: Doubled separating line.

File: cpp/dolfinx/mesh/Topology.cpp [hunk 4]
```diff
@@ -116,62 +116,38 @@ compute_index_sharing(MPI_Comm comm, std::vector<std::int64_t>& unknown_indices)
...
+    throw std::runtime_error("Facet-cell connectivity missing.");
+  std::vector<bool> _boundary_facet(facets->size_local(), false);
+  for (std::size_t f = 0; f < _boundary_facet.size(); ++f)
   {
-    assert(c->num_links(f) == 1 or c->num_links(f) == 2);
-    num_cells0[f] = (c->num_links(f) + owned[f]) > 1 ? 1 : 0;
+    if (fc->num_links(f) == 1
+        and fwd_shared_facets.find(f) == fwd_shared_facets.end())
+    {
+      _boundary_facet[f] = true;
```
Comment (michalhabera) [inline cpp/dolfinx/mesh/Topology.cpp:143]: One-linear could go without the brackets?

File: python/demo/poisson/demo_poisson.py [hunk 5]
```diff
@@ -184,7 +181,9 @@
 
 # Compute solution
 u = Function(V)
-solve(a == L, u, bc, petsc_options={"ksp_type": "preonly", "pc_type": "lu"})
+solve(a == L, u, bc, petsc_options={"ksp_type": "preonly",
+                                    "pc_type": "lu", "pc_factor_mat_solver_type": "superlu_dist"})
```
Comment (michalhabera) [inline python/demo/poisson/demo_poisson.py:185]: Why `superlu_dist` here?

File: python/demo/poisson/demo_poisson.py [hunk 6]
```diff
@@ -197,6 +196,7 @@
 # for later visualization and also plot it using
 # the :py:func:`plot <dolfinx.common.plot.plot>` command: ::
 
+u.vector.ghostUpdate(addv=PETSc.InsertMode.INSERT, mode=PETSc.ScatterMode.FORWARD)
```
Comment (michalhabera) [inline python/demo/poisson/demo_poisson.py:199]: Is ghostUpdate needed after solve(a == L)?

File: python/dolfinx/mesh.py [hunk 7]
```diff
@@ -7,15 +7,14 @@
...
 
 
-def locate_entities_geometrical(mesh: cpp.mesh.Mesh,
-                                dim: int,
-                                marker: types.FunctionType,
-                                boundary_only: bool = False):
+def locate_entities(mesh: cpp.mesh.Mesh,
+                    dim: int,
+                    marker: types.FunctionType,
+                    boundary_only: bool = False):
```
Comment (michalhabera) [inline python/dolfinx/mesh.py:17]: Remove `boundary_only` kwarg, leftover.

File: python/dolfinx/mesh.py [hunk 8]
```diff
@@ -37,7 +36,32 @@ def locate_entities_geometrical(mesh: cpp.mesh.Mesh,
...
     """
 
-    return cpp.mesh.locate_entities_geometrical(mesh, dim, marker, boundary_only)
+    return cpp.mesh.locate_entities(mesh, dim, marker)
+
+
+def locate_entities_boundary(mesh: cpp.mesh.Mesh,
+                             dim: int,
+                             marker: types.FunctionType,
+                             boundary_only: bool = False):
```
Comment (michalhabera) [inline python/dolfinx/mesh.py:45]: Remove `boundary_only` kwarg, leftover.

File: python/test/unit/io/test_xdmf_meshtags.py [hunk 9]
```diff
@@ -13,7 +13,7 @@
 from dolfinx.cpp.mesh import CellType
 from dolfinx.generation import UnitCubeMesh
 from dolfinx.io import XDMFFile
-from dolfinx.mesh import MeshTags, locate_entities_geometrical
+from dolfinx.mesh import MeshTags, locate_entities
```
Comment (michalhabera) [inline python/test/unit/io/test_xdmf_meshtags.py:16]: I think all these and below could be locate_entities_boundary as well

File: python/test/unit/mesh/test_mesh_utils.py [hunk 10]
```diff
@@ -1,393 +0,0 @@
-# Copyright (C) 2020 Garth N. Wells
```
Comment (michalhabera) [inline python/test/unit/mesh/test_mesh_utils.py:1]: Is this removal related to PR?

File: cpp/dolfinx/mesh/utils.h [hunk 11]
```diff
@@ -69,24 +69,48 @@ Eigen::Array<double, Eigen::Dynamic, 3, Eigen::RowMajor> midpoints(
...
+    const std::function<Eigen::Array<bool, Eigen::Dynamic, 1>(
+        const Eigen::Ref<const Eigen::Array<double, 3, Eigen::Dynamic,
+                                            Eigen::RowMajor>>&)>& marker);
+
+/// Compute indicies of all mesh entities that are attached to an owned
+/// boundary facet and evaluate to true for the provided geometric
+/// marking function. An entity is considered marked if the marker
+/// function evaluates true for all of its vertices.
+///
+/// @note For vertices and edges, in parallel this function will not
```
Comment (michalhabera) [inline cpp/dolfinx/mesh/utils.h:93]: Should this note be also in a python docstring? Its important.

File: cpp/dolfinx/mesh/Topology.cpp (hunk 4 above)
Comment (garth-wells) [reply cpp/dolfinx/mesh/Topology.cpp:143]: Not in this case because the preceding statement is over two lines.

File: python/demo/poisson/demo_poisson.py (hunk 6 above)
Comment (garth-wells) [reply python/demo/poisson/demo_poisson.py:199]: It's needed for correct visualisation on the boundaries with `dolfinx.plotting.plot(u)`

File: python/test/unit/mesh/test_mesh_utils.py (hunk 10 above)
Comment (garth-wells) [reply python/test/unit/mesh/test_mesh_utils.py:1]: Yes - it used some removed functionality. It was intended for removal at some point.

File: cpp/dolfinx/mesh/utils.cpp (hunk 2 above)
Comment (garth-wells) [reply cpp/dolfinx/mesh/utils.cpp:828]: It could be optimised for `dim == 0` and `dim == tdim - 1`, but I've made it generic for now. `dim == tdim - 1` is perhaps the most common so could be looked at later.

File: cpp/dolfinx/mesh/Topology.cpp (hunk 3 above)
Comment (garth-wells) [reply cpp/dolfinx/mesh/Topology.cpp:151]: That was actually deliberate - to visually separate the free function from the class members. I've added an extra line now.

File: python/demo/poisson/demo_poisson.py (hunk 5 above)
Comment (garth-wells) [reply python/demo/poisson/demo_poisson.py]: Reverted - I had some trouble with MUMPS and macOS.

**Comment by garth-wells** [comment]
@michalhabera test coverage will come with #1003 being implemented.

File: python/test/unit/io/test_xdmf_meshtags.py (hunk 9 above)
Comment (garth-wells) [reply python/test/unit/io/test_xdmf_meshtags.py:16]: Can you make a separate PR? This PR is a direct translation so I'd rather not look into other tests at this stage.

File: cpp/dolfinx/mesh/utils.h (hunk 11 above)
Comment (garth-wells) [reply cpp/dolfinx/mesh/utils.h:93]: Added.

**Comment by garth-wells** [comment]
I've re-enabled some old test and expanded some existing test to cover ghosted meshes (and fixed some bugs picked up by these)
