### PR TITLE
Use `enabled_coefficients` to restrict packing of coefficients

### LINKED ISSUE #3256: [BUG]: Packing of codim-0 form not working for mixture of measures
### Summarize the issue

Issue is that coefficient packing is not restricted to the integral type.
Thus if you have a coefficient on a subdomain not present in the cell integral (dx), it is still packed for this domain, where the map is undefined. 

### How to reproduce the bug

See mwe below. Will add more info when I got time

### Minimal Example (Python)

```python


from mpi4py import MPI
import dolfinx
import dolfinx.fem.petsc
import ufl
import numpy as np

def half(x):
    return x[1] <= 0.5 + 1e-14


mesh = dolfinx.mesh.create_unit_square(MPI.COMM_WORLD, 2, 2, dolfinx.mesh.CellType.triangle)

# Split domain in half and set an interface tag of 5
gdim = mesh.geometry.dim
tdim = mesh.topology.dim
fdim = tdim - 1
mesh.topology.create_entities(fdim)
num_facets_local = (
    mesh.topology.index_map(fdim).size_local + mesh.topology.index_map(fdim).num_ghosts
)
facets = np.arange(num_facets_local, dtype=np.int32)
values = np.full_like(facets, 0, dtype=np.int32)

bottom_cells = dolfinx.mesh.locate_entities(mesh, tdim, half)
num_cells_local = (
    mesh.topology.index_map(tdim).size_local + mesh.topology.index_map(tdim).num_ghosts
)
cells = np.full(num_cells_local, 4, dtype=np.int32)
cells[bottom_cells] = 3
ct = dolfinx.mesh.meshtags(
    mesh, tdim, np.arange(num_cells_local, dtype=np.int32), cells
)
all_b_facets = dolfinx.mesh.compute_incident_entities(
    mesh.topology, ct.find(3), tdim, fdim
)
all_t_facets = dolfinx.mesh.compute_incident_entities(
    mesh.topology, ct.find(4), tdim, fdim
)
interface = np.intersect1d(all_b_facets, all_t_facets)
values[interface] = 5

mt = dolfinx.mesh.meshtags(mesh, mesh.topology.dim - 1, facets, values)

submesh_b, submesh_b_to_mesh, b_v_map = dolfinx.mesh.create_submesh(
    mesh, tdim, ct.find(3)
)[0:3]
submesh_t, submesh_t_to_mesh, t_v_map = dolfinx.mesh.create_submesh(
    mesh, tdim, ct.find(4)
)[0:3]
parent_to_sub_b = np.full(num_facets_local, -1, dtype=np.int32)
parent_to_sub_b[submesh_b_to_mesh] = np.arange(len(submesh_b_to_mesh), dtype=np.int32)
parent_to_sub_t = np.full(num_facets_local, -1, dtype=np.int32)
parent_to_sub_t[submesh_t_to_mesh] = np.arange(len(submesh_t_to_mesh), dtype=np.int32)    

# We need to modify the cell maps, as for `dS` integrals of interfaces between submeshes, there is no entity to map to.
# We use the entity on the same side to fix this (as all restrictions are one-sided)

# Hack, as we use one-sided restrictions, pad dS integral with the same entity from the same cell on both sides
mesh.topology.create_connectivity(fdim, tdim)
f_to_c = mesh.topology.connectivity(fdim, tdim)
for facet in mt.find(5):
    cells = f_to_c.links(facet)
    assert len(cells) == 2
    b_map = parent_to_sub_b[cells]
    t_map = parent_to_sub_t[cells]
    assert max(b_map) > -1
    assert max(t_map) > -1
    parent_to_sub_b[cells] = max(b_map)
    parent_to_sub_t[cells] = max(t_map)

entity_maps = {submesh_b._cpp_object: parent_to_sub_b, submesh_t._cpp_object: parent_to_sub_t}

V_0 = dolfinx.fem.functionspace(submesh_b, ("Lagrange", 3))
V_1 = dolfinx.fem.functionspace(submesh_t, ("Lagrange", 2))

c_0 = dolfinx.fem.Function(V_0)
c_1 = dolfinx.fem.Function(V_1)
c_0.name = "c_0"
c_0.x.array[:] = 2
c_1.name = "c_1"
c_1.x.array[:] = 5

v_0 = ufl.TestFunction(V_0)
v_1 = ufl.TestFunction(V_1)

ct = dolfinx.mesh.meshtags(mesh, tdim, submesh_b_to_mesh, np.full_like(submesh_b_to_mesh, 1,dtype=np.int32))
dx = ufl.Measure("dx", domain=mesh, subdomain_data=ct, subdomain_id=1)
dInterface = ufl.Measure("dS", domain=mesh, subdomain_data=mt, subdomain_id=5)
b_res = "+"
t_res = "-"

c_1_r = c_1(t_res)
v_0_r = v_0(b_res)
v_1_r = v_1(t_res)

F = ufl.inner(c_0, v_0) * dx + ufl.inner(c_1_r, v_0_r) * dInterface
F_c = dolfinx.fem.form(F, entity_maps=entity_maps)

print(dolfinx.fem.assemble.pack_coefficients(F_c._cpp_object))
print(dolfinx.fem.petsc.assemble_vector(F_c))

```

### Output (Python)

_No response_

### Version

main branch

### DOLFINx git commit

_No response_

### Installation

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jorgensd**
Pack only entities used in integral type:
MWE:
```python
from mpi4py import MPI
import dolfinx
import ufl

mesh = dolfinx.mesh.create_unit_cube(MPI.COMM_WORLD, 50, 50, 50)
V = dolfinx.fem.functionspace(mesh, ("Lagrange", 3))
N = 50
us = [dolfinx.fem.Function(V) for _ in range(N)]
for i,u in enumerate(us):
    u.x.array[:] = i + 1
    u.name=f"u_{i}"

volume_form = us[0] * ufl.dx
surface_form = sum(us[i] * ufl.ds for i in range(N))

combined_form = volume_form + surface_form
compiled_form = dolfinx.fem.form(combined_form)

import time
start = time.perf_counter()
coeffs = dolfinx.fem.assemble.pack_coefficients(compiled_form._cpp_object)
end =time.perf_counter()
print(f"{dolfinx.common.git_commit_hash=} {end-start=:.5e}")
print(coeffs[(dolfinx.fem.IntegralType.cell, -1)])
```
On the main branch, all coefficients are packed for the cell integral, even if only the first coefficient is used in that integral.
Runtime on this branch:
```bash
dolfinx.common.git_commit_hash='002e1fa9360995f9c71414a683e7ce618d6101e9' end-start=1.70250e+00
```
on main
```bash
dolfinx.common.git_commit_hash='64e35310085683f4f61804e70b8b58b9bb8653ae' end-start=2.89335e+00
```
It would also resolve #3256 and simplify some logic in: #3224

### CODE REVIEW

File: cpp/dolfinx/fem/Form.h [hunk 1]
```diff
@@ -49,30 +49,39 @@ struct integral_data
   /// @param id Domain ID.
   /// @param kernel Integration kernel.
   /// @param entities Entities to integrate over.
-  template <typename K, typename V>
+  /// @param enabled_coefficients Coefficients in form that are enabled in this
+  /// integral
+  template <typename K, typename V, typename Q>
```
Comment (garth-wells) [inline cpp/dolfinx/fem/Form.h:54]: What is `Q`? For the other templated args we use concepts to constrain what they must be able to do.

File: cpp/dolfinx/fem/Form.h [hunk 2]
```diff
@@ -49,30 +49,39 @@ struct integral_data
...
                  and std::is_convertible_v<std::remove_cvref_t<V>,
                                            std::vector<std::int32_t>>
-  integral_data(int id, K&& kernel, V&& entities)
+                 and std::is_convertible_v<std::remove_cvref_t<Q>,
+                                           std::vector<std::int8_t>>
+  integral_data(int id, K&& kernel, V&& entities, Q&& enabled_coefficients)
       : id(id), kernel(std::forward<K>(kernel)),
-        entities(std::forward<V>(entities))
+        entities(std::forward<V>(entities)),
+        enabled_coefficients(std::move(enabled_coefficients))
```
Comment (garth-wells) [inline cpp/dolfinx/fem/Form.h:66]: `std::move` here is wrong - check how the other cases are handled.

File: cpp/dolfinx/fem/Form.h [hunk 3]
```diff
@@ -49,30 +49,39 @@ struct integral_data
...
   {
   }
 
   /// @brief Create a structure to hold integral data.
   /// @param id Domain ID
   /// @param kernel Integration kernel.
   /// @param e Entities to integrate over.
+  /// @param c Coefficients in form that are enabled in this
```
Comment (garth-wells) [inline cpp/dolfinx/fem/Form.h:74]: Not clear what `c` is. Is it the coefficient indices?

File: cpp/dolfinx/fem/Form.h [hunk 4]
```diff
@@ -86,6 +95,9 @@ struct integral_data
 
   /// The entities to integrate over
   std::vector<std::int32_t> entities;
+
+  /// Indicator of which coefficients (from the form) that is in this integral
```
Comment (garth-wells) [inline cpp/dolfinx/fem/Form.h:99]: See above question on what  enabled_coefficients is.

File: cpp/dolfinx/fem/Form.h [hunk 5]
```diff
@@ -281,6 +293,19 @@ class Form
...
+  /// (kernel).
+  /// @param[in] type Integral type.
+  /// @param[in] i The index of the integral.
+  std::span<const std::int8_t> enabled_coefficients(IntegralType type,
+                                                    std::size_t i) const
+  {
+    assert(i < _integrals[static_cast<std::size_t>(type)].size());
+    const std::vector<std::int8_t>& enabled_coeffs
+        = _integrals[static_cast<std::size_t>(type)][i].enabled_coefficients;
+    return std::span<const std::int8_t>(enabled_coeffs.data(),
```
Comment (garth-wells) [inline cpp/dolfinx/fem/Form.h:306]: This looks shaky from a memory safety perspective. 

How big is `enabled_coeffs` likely to be?

File: cpp/dolfinx/fem/utils.h [hunk 6]
```diff
@@ -418,6 +418,11 @@ Form<T, U> create_form_factory(
       ufcx_integral* integral
           = ufcx_form.form_integrals[integral_offsets[cell] + i];
       assert(integral);
+      const bool* _enabled_coefficients = integral->enabled_coefficients;
```
Comment (garth-wells) [inline cpp/dolfinx/fem/utils.h:421]: Nothing wrong with this, but we should probably replace `bool` by `uint8_t` in UFCx.

File: cpp/dolfinx/fem/utils.h [hunk 7]
```diff
@@ -418,6 +418,11 @@ Form<T, U> create_form_factory(
...
+      // Get list of enabled coefficients
+      std::vector<std::int8_t> enabled_coefficients(ufcx_form.num_coefficients);
```
Comment (garth-wells) [inline cpp/dolfinx/fem/utils.h:423]: This and other lines of code can be replaced by
```cpp
std::vector<std::int8_t> enabled_coefficients(integral->enabled_coefficients, integral->enabled_coefficients + ufcx_form.num_coefficients);
```

**Review by garth-wells — CHANGES_REQUESTED** [review]

File: cpp/dolfinx/fem/Form.h (hunk 4 above)
Comment (jorgensd) [reply cpp/dolfinx/fem/Form.h:99]: Enabled coefficients is a list of booleans, corresponding to the N coefficients in the form. 
As each form is split into M integrals, not every integral uses every coefficient.

File: cpp/dolfinx/fem/Form.h (hunk 5 above)
Comment (jorgensd) [reply cpp/dolfinx/fem/Form.h:306]: It is the number of unique coefficients in your form. I would be suprised if this hits more than 100.

File: cpp/dolfinx/fem/utils.h (hunk 6 above)
Comment (jorgensd) [reply cpp/dolfinx/fem/utils.h:421]: Could we do that in a separate PR, as this keeps the current interface (and could therefore in theory be backported).

File: cpp/dolfinx/fem/Form.h (hunk 1 above)
Comment (jorgensd) [reply cpp/dolfinx/fem/Form.h:54]: I am not sure what you are after here. We need the input to be convertible to a `std::vector<std::int8_t>`. What would you do differently?

File: cpp/dolfinx/fem/Form.h (hunk 2 above)
Comment (jorgensd) [reply cpp/dolfinx/fem/Form.h:66]: It is quite small, number of unique coefficients.

File: cpp/dolfinx/fem/Form.h (hunk 5 above)
Comment (jorgensd) [reply cpp/dolfinx/fem/Form.h:312]: Could you elaborate on why this is shaky?

Comment (garth-wells) [reply cpp/dolfinx/fem/Form.h:312]: Spans of objects of objects. 

Since it's small, it would be much simpler to make it a `std::vector`. Negligible cost and memory safe.

File: cpp/dolfinx/fem/Form.h (hunk 1 above)
Comment (garth-wells) [reply cpp/dolfinx/fem/Form.h:54]: Did I miss the `std::is_convertible_v<std::remove_cvref_t<Q>, ...` on my first pass?

File: python/test/unit/fem/test_custom_jit_kernels.py [hunk 8]
```diff
@@ -128,7 +129,10 @@ def test_coefficient(dtype):
 
     tdim = mesh.topology.dim
     num_cells = mesh.topology.index_map(tdim).size_local + mesh.topology.index_map(tdim).num_ghosts
-    integrals = {IntegralType.cell: [(1, k1.address, np.arange(num_cells, dtype=np.int32))]}
+    active_coeffs = np.array([1], dtype=np.int8)
```
Comment (jorgensd) [inline python/test/unit/fem/test_custom_jit_kernels.py:132]:
```suggestion
    active_coeffs = np.array([0], dtype=np.int8)
```

File: python/demo/demo_static-condensation.py [hunk 9]
```diff
@@ -162,7 +162,7 @@ def tabulate_A(A_, w_, c_, coords_, entity_local_index, permutation=ffi.NULL):
 # Prepare a Form with a condensed tabulation kernel
 formtype = form_cpp_class(PETSc.ScalarType)  # type: ignore
 cells = np.arange(msh.topology.index_map(msh.topology.dim).size_local)
-integrals = {IntegralType.cell: [(-1, tabulate_A.address, cells)]}
+integrals = {IntegralType.cell: [(-1, tabulate_A.address, cells, np.array([], dtype=np.int8))]}
```
Comment (jorgensd) [inline python/demo/demo_static-condensation.py:165]:
```suggestion
integrals = {IntegralType.cell: [(-1, tabulate_A.address, cells, np.array([], dtype=np.int32))]}
```

**Comment by jorgensd** [comment]
Running the test above in serial on my system:
Main: 
```bash
dolfinx.common.git_commit_hash='90e4fee36c2f5d1254ceec4638fd4194cc8be7da' end-start=2.90846e+01
```

This PR
```bash
dolfinx.common.git_commit_hash='9f19213e8b4d6e586601dd8d1ce40b37da948aa1' end-start=6.47885e+00
```

**Review by garth-wells — APPROVED** [review]
